import Head from 'next/head'
import Image from 'next/image'
import Box from '../components/Box'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scroll Animation | Framer Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Scroll Animation</h1>

      <div
        style={{
          marginTop: "50px",
          marginBottom: "50px"
        }}  
      >
        pickled artisan. Plaid you probably haven't heard of them hell of JOMO enamel pin fam health goth tumeric farm-to-table authentic selvage activated charcoal. Kale chips cliche af keytar. Brunch readymade austin selvage. Mustache lo-fi green juice locavore pour-over.
      </div>

      <div
        style={{
          marginTop: "50px",
          marginBottom: "50px"
        }}  
      >
        pickled artisan. Plaid you probably haven't heard of them hell of JOMO enamel pin fam health goth tumeric farm-to-table authentic selvage activated charcoal. Kale chips cliche af keytar. Brunch readymade austin selvage. Mustache lo-fi green juice locavore pour-over.
      </div>

      <div
        style={{
          marginTop: "50px",
          marginBottom: "50px"
        }}  
      >
        pickled artisan. Plaid you probably haven't heard of them hell of JOMO enamel pin fam health goth tumeric farm-to-table authentic selvage activated charcoal. Kale chips cliche af keytar. Brunch readymade austin selvage. Mustache lo-fi green juice locavore pour-over.
      </div>

      <div
        style={{
          marginTop: "50px",
          marginBottom: "50px"
        }}  
      >
        pickled artisan. Plaid you probably haven't heard of them hell of JOMO enamel pin fam health goth tumeric farm-to-table authentic selvage activated charcoal. Kale chips cliche af keytar. Brunch readymade austin selvage. Mustache lo-fi green juice locavore pour-over.
      </div>


      <div className='boxContainer'>
        <Box num={1} />
        <Box num={2} />
      </div>

    </div>
  )
}
