import Head from 'next/head'
import Image from 'next/image'
import Box from '../components/Box'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Scroll Animation | Framer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Scroll Animation</h1>

      <div
        style={{
          marginTop: "50px",
          marginBottom: "50px"
        }}  
      >
        <img
          src="https://wallpapers.com/images/hd/hd-black-aesthetic-artwork-6z5hatpbqvrocass.jpg"
        />
      </div>

      <div className='boxContainer'>
        <Box num={1} />
        <Box num={2} />
      </div>

    </div>
  )
}
